In [1]:
import numpy as np

**Element wise matrix addition**

In [2]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
addition = a + b
print("Sum of a and b:\n",addition)

Sum of a and b:
 [[ 6  8]
 [10 12]]


**Element wise matrix subtraction**

In [6]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
difference = a - b
print("Difference of a and b:\n",difference)

Difference of a and b:
 [[-4 -4]
 [-4 -4]]


**Element wise matrix multiplication**

In [5]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
product = np.dot(a,b)
print("Product of a and b matrix:\n",product)

Product of a and b matrix:
 [[19 22]
 [43 50]]


In [7]:
new_prod =a @ b
print(new_prod)

[[19 22]
 [43 50]]


In [8]:
new_prod = a * b
print(new_prod)

[[ 5 12]
 [21 32]]


In [11]:
mat1 = np.array([[1,2,3]])
mat2 = np.array([[1],[2],[3]])
product = np.dot(mat1,mat2)
normal_product = mat1 * mat2
print("Dot product: ",product)
print("Normal product:\n",normal_product)

Dot product:  [[14]]
Normal product:
 [[1 2 3]
 [2 4 6]
 [3 6 9]]


**Multiplying using different row and column**

In [ ]:
mat1 = np.array([1,2,3])
mat2 = np.array([[1,2,3]])
product = mat1 @ mat2
print("Product: \n",product) # this one will result error because the n of mat1 doesnot matches the m of mat2   

**Element wise division in matrix**

In [14]:
mat1 = np.array([1,2,3])
mat2 = np.array([[1,2,3]])
division = mat1 / mat2
print("Division of mat1 and mat2:\n",division)

Division of mat1 and mat2:
 [[1. 1. 1.]]


In [ ]:
mat1 = np.array([[1,2,3]])
mat2 = np.array([[1],[2],[3]])
division = mat1 / mat2
print("Division of mat1 and mat2:\n",division)

Division of mat1 and mat2:
 [[1.         2.         3.        ]
 [0.5        1.         1.5       ]
 [0.33333333 0.66666667 1.        ]]


# **Scalar**

In [21]:
scalar = 2
mat1 = np.array([[1,2,3]])
result_add = mat1 + scalar
print("After adding by scalar value:\n",result_add)
result_product = mat1 * scalar
print("After multiplying by scalar value:\n",result_product)
result_difference = mat1 / scalar
print("After dividing by scalar value:\n",result_difference)

After adding by scalar value:
 [[3 4 5]]
After multiplying by scalar value:
 [[2 4 6]]
After dividing by scalar value:
 [[0.5 1.  1.5]]


In [24]:
a = np.array([[1,2],[3,4]])
b = np.array([1,2])
sum = a + b
print(sum)

[[2 4]
 [4 6]]


# **Linear Algebra**

linear algebra means mathematical expression.Eg:
- 2x + y = 5
- x + 3y = 6

In [ ]:
A = np.array([[2,1],
              [1,3]
            ])
B = np.array([5,6])
x = np.linalg.solve(A,B)
print(f"x: {x[0]}\ny: {x[1]}")

A: 1.8
B: 1.4


In [31]:
A = np.array([[1,1,2,1,1],[2,-1,1,3,2],[1,2,1,-1,1],[3,1,2,1,-1],[1,-1,1,2,3]])
B = np.array([5,8,4,10,7])
X = np.linalg.solve(A,B)
print("Value of u:",X[0])
print("Value of v:",X[1])
print("Value of x:",X[2])
print("Value of y:",X[3])
print("Value of z:",X[4])

Value of u: 3.375
Value of v: -1.9166666666666654
Value of x: 2.083333333333332
Value of y: -1.499999999999999
Value of z: 0.8750000000000002


In [ ]:
x = np.array([[1,1],[2,1],[3,1]])
y = np.array([[2],[3],[5]])
final_product = np.linalg.inv(x.T @ x) @ x.T @ y
print("Slope (m):",final_product[0])
print("Interception (c):",final_product[1])

Slope (m): [1.5]
Interception (c): [0.33333333]


**Determinant of a matrix**

In [51]:
a = np.array([[1,2],[4,5]])
print("Determinant of a: ",np.linalg.det(a))
print("Inverse of a:\n",np.linalg.inv(a))

Determinant of a:  -2.9999999999999996
Inverse of a:
 [[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


**Eigen Values and Eigen Vectors**

In [54]:
a = np.array([[1,2],[4,5]])
eigen = np.linalg.eig(a)
print("Eigen values:",eigen[0])
print("Eigen vector:\n",eigen[1])

Eigen values: [-0.46410162  6.46410162]
Eigen vector:
 [[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


**SVD (Single Value Decomposition)**

In [60]:
u,s,v = np.linalg.svd(a)
print("Value of u:\n",u)
print("Value of s:\n",s)
print("Value of v:\n",v)

Value of u:
 [[-0.32453643 -0.9458732 ]
 [-0.9458732   0.32453643]]
Value of s:
 [6.76782894 0.44327362]
Value of v:
 [[-0.60699365 -0.79470668]
 [ 0.79470668 -0.60699365]]
