In [1]:
# importing numpy for further uses
import numpy as np

**Create two 3 x 3 matrices and perform matrix addition**

In [2]:
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2 = np.array([[4,5,6],[2,1,3],[9,7,8]])
sum = mat1 + mat2
print("After matrix addition:\n",sum)

After matrix addition:
 [[ 5  7  9]
 [ 6  6  9]
 [16 15 17]]


**Find the transpose of a 2 x 4 matrix**

In [3]:
mat1 = np.array([[1,2,3,4],[5,6,7,8]])
transposed = mat1.T
print("Before transpose:\n",mat1)
print("After transpose:\n",transposed)

Before transpose:
 [[1 2 3 4]
 [5 6 7 8]]
After transpose:
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


**Calculate the determinant of 2 x 2 matrix**

In [4]:
mat1 = np.array([[1,2],[3,4]])
print("Determinant of mat:",np.linalg.det(mat1))

Determinant of mat: -2.0000000000000004


**Find the inverse of a matrix and verify the result**

In [5]:
mat1 = np.array([[1,2],[3,4]])
inv = np.linalg.inv(mat1)
print("Inverse of mat1:\n",inv)

Inverse of mat1:
 [[-2.   1. ]
 [ 1.5 -0.5]]


**Create a 4 x 4 identity matrix**

In [7]:
matrix = np.eye(4,4)
print("4 x 4 identity matrix:\n",matrix)

4 x 4 identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Find the rank of a given matrix**

In [33]:
matrix = np.random.rand(1,10).reshape(5,2)
print("Rank of matrix: ",np.linalg.matrix_rank(matrix))

Rank of matrix:  2


**Compute the trace of matrix**

In [12]:
A = np.array([[2,3,4],[1,5,6],[7,8,9]])
trace = np.trace(A)
print("Trace (sum of diagonal elements): ",trace)

Trace (sum of diagonal elements):  16


**Find eigenvalues and eigenvectors of a 2 x 2 matrix**

In [13]:
A = np.array([[2,3,4],[1,5,6],[7,8,9]])
eigen_value,eigen_vector = np.linalg.eig(A)
print("Eigen Values:\n",eigen_value)
print("Eigen Vector:\n",eigen_vector)

Eigen Values:
 [16.31146204  0.81578887 -1.12725091]
Eigen Vector:
 [[-0.32738499 -0.32549255 -0.28502223]
 [-0.46519555  0.80017165 -0.64647793]
 [-0.8224428  -0.50376576  0.70769246]]


**Solve a system of linear equation using np.linalg.solve()**
- 2x + y = 5
- x - y = 1

In [14]:
A = np.array([[2,1],[1,-1]])
B = np.array([5,1])
x,y = np.linalg.solve(A,B)
print("value of x: ",x)
print("value of y: ",y)

value of x:  2.0
value of y:  1.0


**Perform SVD on a 3 x 3 matrix and print U,S and T** 

In [16]:
A = np.array([[2, 1, -1],
              [3, 0, 2],
              [1, 1, 1]])
u,s,t = np.linalg.svd(A)
print("Value of u: \n",u)
print("Value of s: \n",s)
print("Value of t: \n",t)


Value of u: 
 [[-0.37899706  0.92144154 -0.08547936]
 [-0.85204859 -0.38350624 -0.35628101]
 [-0.36107399 -0.06219689  0.93046071]]
Value of s: 
 [4.11072809 2.04943676 0.94959128]
Value of t: 
 [[-0.89405424 -0.18003406 -0.41018868]
 [ 0.30748324  0.41925892 -0.85421075]
 [-0.32576229  0.88983689  0.31948276]]


**Calculate the norm of a vector.**

In [18]:
vector = np.array([3, 4, 5])
print("Normalization of vector:",np.linalg.norm(vector))

Normalization of vector: 7.0710678118654755


**Find the dot product of two vectors.**

In [19]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
dot_product = np.dot(a,b)
print("Dot product:\n",dot_product)

Dot product:
 [[19 22]
 [43 50]]


**Find cross product of two 3D vectors**

In [ ]:
a = np.array([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
b = np.array([[
    [3,1,2],
    [5,6,4],
    [8,9,7]
]])
cross_product = np.cross(a,b)
print("Cross product:\n",cross_product)

3
Cross product:
 [[[  1   7  -5]
  [-16  14  -1]
  [-25  23  -1]]]


**Multiply matrices using @**

In [23]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
product = a @ b
print("Matrix multiplication of a and b:\n",product)

Matrix multiplication of a and b:
 [[19 22]
 [43 50]]


**Verify that A @ np.linalg.inv(A) produces an identity matrix.**

In [32]:
A = np.array([[1,2],[3,4]])
inv_A = np.linalg.inv(A)
prod = A @ inv_A
identity_matrix = np.eye(2,2)
prod = np.rint(prod).astype(int)
if np.array_equal(prod,identity_matrix):
    print("Yes, matrix * its inverse = identity matrix.")
else:
    print("No, matrix * its inverse != identity matrix.")


Yes, matrix * its inverse = identity matrix.
