# **Practice Questions**

In [1]:
# importing numpy for further uses
import numpy as np

**Create a NumPy array:**
[[10,20,30],
[40,50,60]]
 
**Find the shape, ndim and dtype** 

In [2]:
nums_arr = np.array([
    [10,20,30],
    [40,50,60]
])
print("Shape:",nums_arr.shape)
print("Dimension:",nums_arr.ndim)
print("Dtype:",nums_arr.dtype)

Shape: (2, 3)
Dimension: 2
Dtype: int64


[1,2,3,4,5,6,7,8]

**Reshape it into a 2 x 4 matrix and then convert it back to a 1D array using ravel()**

In [5]:
nums = [1,2,3,4,5,6,7,8]
reshaped = np.reshape(nums,(2,4))
print("Reshaped:\n",reshaped)
reshaped_back = np.ravel(nums)
print("Reshaped into 1D:",reshaped_back)

Reshaped:
 [[1 2 3 4]
 [5 6 7 8]]
Reshaped into 1D: [1 2 3 4 5 6 7 8]


[5,10,15,20,25]

**Find the sum, cumulative sum and product of all element**

In [6]:
nums = [5,10,15,20,25]
print("Sum:",np.sum(nums))
print("Cumulative sum:",np.cumsum(nums))
print("Product of all elements:",np.prod(nums))

Sum: 75
Cumulative sum: [ 5 15 30 50 75]
Product of all elements: 375000


[12,45,22,78,34]

**Find the maximum value,index of maximum value and clip the values between 20 and 50**

In [12]:
nums = [12,45,22,78,34]
print("Maximum value: ",np.max(nums))
print("Index of maximum value: ",nums[np.argmax(nums)])
print("After clipping values between 20 and 50:",np.clip(nums,20,50))

Maximum value:  78
Index of maximum value:  78
After clipping values between 20 and 50: [20 45 22 50 34]


[1,2,3,4,5,6]

**Split array into 3 equal parts using np.split**

In [20]:
nums = [1,2,3,4,5,6]
print(np.array_split(nums,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


a = [1,2,3]

b = [4,5,6]

**Concatenate them, stack them vertically and stack them horizontally**

In [26]:
a = np.array([1,2,3])
b = np.array([4,5,6])
concatenated = np.concat((a,b))
print("Concatenated:\n",concatenated)
print("Vertically stacked:\n",np.vstack((a,b)))
print("Horizontally stacked:\n",np.hstack((a,b)))

Concatenated:
 [1 2 3 4 5 6]
Vertically stacked:
 [[1 2 3]
 [4 5 6]]
Horizontally stacked:
 [1 2 3 4 5 6]
