# **Introduction to NumPy**

**importing numpy**

In [1]:
import numpy as np

In [2]:
# creating 1D array from numpy
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [5]:
# creating 2D array from numpy
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [9]:
# creating 3D array from numpy
a = np.array([
    [[1,2,3],[4,5,6]],
     [[7,8,9],[10,11,12]]
])
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#**list vs NumPy Array**

- Element wise multiplication

In [11]:
py_list = [1,2,3]
print("Python list multiplication: ",py_list * 2)

np_arr = np.array([1,2,3])
print("NumPy Array multiplication: ",np_arr * 2)

Python list multiplication:  [1, 2, 3, 1, 2, 3]
NumPy Array multiplication:  [2 4 6]


- List are of 1D whereas Array can be of multiple dimension

#**Time speed comparison of numpy operation and python list**

In [22]:
import time
start = time.time()
py_list = [i * 2 for i in range(100000000)]
print("Time taken by python list: ",(time.time() - start))

Time taken by python list:  4.1781768798828125


In [23]:
start = time.time()
np_arr = np.arange(100000000) * 2
print("Time taken by numpy array: ",(time.time() - start))

Time taken by numpy array:  0.1902928352355957


In [24]:
start = time.time()
py_list = [i ^ 4 for i in range(10000000)]
print("Time taken by python list", (time.time() - start))

Time taken by python list 1.1330673694610596


In [25]:
start = time.time()
np_arr = np.arange(10000000) ^ 4
print("Time taken by python list", (time.time() - start))

Time taken by python list 0.043009042739868164


#**Rank**

In [27]:
# Rank 0 => Scalar
a = np.array(10)
a.ndim

0

In [29]:
# Rank 1 => Vector
a = np.array([10,20])
a.ndim

1

In [35]:
# Rank 2 => Matrix
a = np.array([
    [10,20],
     [30,40]
])
print(f"Dimension : {a.ndim}\nShape : {a.shape}")

Dimension : 2
Shape : (2, 2)


#**Class Task: Creating 5 x 5 matrix and see the rank**

In [38]:
a  = np.array([
    [1,2,3,4,5],
    [6,7,8,9,0],
    [1,3,2,4,5],
    [5,6,4,2,1],
    [8,6,5,4,7]
])
print("Rank:",a.ndim)
print("Shape:",a.shape)

Rank: 2
Shape: (5, 5)


# **Real-life Example**
- Creating zeros

In [42]:
zeros = np.zeros((3,4))
print("Matrix:\n",zeros)
print("Dimension:",zeros.ndim)
print("Shape:",zeros.shape)

Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Dimension: 2
Shape: (3, 4)


In [43]:
zeros = np.zeros((4,5))
print("Matrix:\n",zeros)
print("Dimension:",zeros.ndim)
print("Shape:",zeros.shape)

Matrix:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Dimension: 2
Shape: (4, 5)


- Creating ones

In [44]:
ones = np.ones((4,5))
print("Matrix:\n",ones)
print("Dimension:",ones.ndim)
print("Shape:",ones.shape)

Matrix:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Dimension: 2
Shape: (4, 5)


In [49]:
ones = np.ones((4,5,6))
print(ones)

[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]


#**Converting datatypes into integer**

In [47]:
# creating in integer format
np.ones(shape=(4,5),dtype = "int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# **sum using axis**

- sum using axis = 0 (column)

In [50]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
print(a.sum(axis = 0))

[5 7 9]


- sum using axis = 1 (row)

In [52]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
print(a.sum(axis = 1))

[ 6 15]


# **Creating random elements array**

In [57]:
np.random.random((2,5))

array([[0.96166822, 0.82726655, 0.29466163, 0.82463933, 0.23190139],
       [0.86050972, 0.01073519, 0.98873701, 0.75014539, 0.92973814]])

# **Numpy array creation method**

- arange()

In [83]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

- full()

In [59]:
np.full((2,3),fill_value = 3)

array([[3, 3, 3],
       [3, 3, 3]])

- linspace()

In [84]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

- diag()

In [75]:
np.diag([1,1,1])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

- eye()

In [81]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

- identity()

In [80]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

- random.rand

In [94]:
np.random.rand(3,4)

array([[0.70632421, 0.02093295, 0.39233971, 0.64433978],
       [0.09822738, 0.08113233, 0.16700989, 0.76281456],
       [0.38164856, 0.55933836, 0.89392208, 0.82333648]])

# **difference between eye() and identity()**

In [87]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [91]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])