# **Class Tasks**

In [1]:
# importing numpy for using below
import numpy as np

**Create a 1D NumPy array containing the values: 10,20,30,40,50**

In [3]:
np_arr = np.array([10,20,30,40,50])
print("1D array: ",np_arr)

1D array:  [10 20 30 40 50]


**Create a 2D NumPy array representing the following matrix:**
- 1 2 3
- 4 5 6
- 7 8 9

In [4]:
np_twod_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array:\n",np_twod_arr)

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


**Create a NumPy array of shape (3,4) filled entirely with zeros**

In [7]:
zeros = np.zeros((3,4))
print("Array with shape (3,4) entirely filled with zeros: \n",zeros)

Array with shape (3,4) entirely filled with zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Using NumPy's arange() function, create an array containing odd numbers from 1 to 19**

In [8]:
odd_numbers = np.arange(1,20,2)
print("Array of odd numbers from 1 to 19 using arange() function:\n",odd_numbers)

Array of odd numbers from 1 to 19 using arange() function:
 [ 1  3  5  7  9 11 13 15 17 19]


**Using NumPy's linspace() function, create an array of 5 evenly spaced values between 0 and 100**

In [10]:
evenly_spaced = np.linspace(0,100,5,dtype="int")
print("5 numbers between 0 and 100 evenly spaced are:\n",evenly_spaced)

5 numbers between 0 and 100 evenly spaced are:
 [  0  25  50  75 100]


# **Practise Question**

**Use the numpy add function to add the values 34 and 29 in the cell below.**

In [12]:
a = np.array(34)
b = np.array(29)
sum = np.add(a,b)
print(f"Sum = {sum}")

Sum = 63


**Declare a new array with contents [5,4,3,2,1] and slice it to select the last 3 items**

In [14]:
arr = np.array([5,4,3,2,1])
print("Last 3 items :",arr[2:])

Last 3 items : [3 2 1]


**Select all elements in the array below excluding the last one**

In [15]:
arr = np.array([5,4,3,2,1])
print("Last 3 items :",arr[:-1])

Last 3 items : [5 4 3 2]


**Use arr as defined in 2.3. Exclude the last element from the list, but now only select every 3rd element. Remember the third index indicates stride**

In [21]:
arr = np.array([5,4,3,2,1,4,2])
print("Array without last element from the list and every third element:\n",arr[:-1:3] )

Array without last element from the list and every third element:
 [5 2]


**You'll need to combine array comparison and logical opeartors to solve this one. Find out the values in the following array that are greater than 3 and less than 7. The output should be a boolean array**

In [20]:
arr = np.array([5,4,3,2,1])
new_arr = np.array([True if 3 < i < 7 else False for i in arr ])
print("Boolean array where value are greater than 3 and less than 7:\n",new_arr)

Boolean array where value are greater than 3 and less than 7:
 [ True  True False False False]
